const images = {
    logo: require('../assets/icons/Smart.png'), 
    lock: require('../assets/icons/auto_login.png'), 
    mobile_bg: require('../assets/icons/Login/mobile_bg.png'),
    menu_icon: require('../assets/icons/CustomerList/menu_icon.png'),
    refresh_icon: require('../assets/icons/CustomerList/refresh.png'),
    backnav_icon: require('../assets/icons/back_nav.png'), 
    locked_icon: require('../assets/icons/locked.png'), 
    rowclick_icon: require('../assets/icons/CustomerList/row_clickable.png'),
    updown_icon: require('../assets/icons/CustomerList/updown.png'), 
    overview_icon: require('../assets/icons/Purchase/overview.png'),
    search_icon: require('../assets/icons/search.png'), 
    camera_icon: require('../assets/icons/Purchase/camera.png'), 
    delete_icon: require('../assets/icons/delete.png'), 
    threedot_icon: require('../assets/icons/three_dot.png'), 
    arrowup_icon: require('../assets/icons/arrow_up.png'),
    arrowdown_icon: require('../assets/icons/arrow_down.png'),
    split_icon: require('../assets/icons/split.png'),
    remove_icon: require('../assets/icons/remove.png'),
    add_icon: require('../assets/icons/add.png'), 
    row_arrow_icon: require('../assets/icons/right_arrow.png'), 
    close_icon: require('../assets/icons/close_icon.png'), 
    send_icon: require('../assets/icons/Other/send.png'), 
    qrcode_icon: require('../assets/icons/qrcode.png'), 
    manual_icon: require('../assets/icons/manual.png'), 
    barcode_icon: require('../assets/icons/barcode.png'),
    barcode_icon: require('../assets/icons/barcode.png'),
    sync_articles_icon: require('../assets/icons/Sidemenu/sync_articles.png'), 
    find_material_icon: require('../assets/icons/Sidemenu/find_material.png'), 
    customer_drawer_icon: require('../assets/icons/Sidemenu/customer_drawer.png'), 
    find_information_icon: require('../assets/icons/Sidemenu/find_information.png'), 
    sign_out_icon: require('../assets/icons/Sidemenu/signout.png'), 
    lang: require('../assets/icons/lang.png'), 
    trash_icon: require('../assets/icons/trash.png'),
    edit_icon: require('../assets/icons/edit.png'), 
    verfied_icon: require('../assets/icons/verifed.png'), 
    waiting_icon: require('../assets/icons/CustomerList/waiting.png'), 
    intransit_icon: require('../assets/icons/CustomerList/intransit.png'),
    invoicepending_icon: require('../assets/icons/CustomerList/invoicepending.png'),
    processing_icon: require('../assets/icons/CustomerList/processing.png'), 
    touch_icon: require('../assets/img/touch.png'), 
    calender: require('../assets/icons/calander.png'), 
    company: require('../assets/icons/company.png'), 
    home: require('../assets/icons/home.png'),
    userInformation: require('../assets/icons/userinformation.png'), 
    station: require('../assets/icons/station.png'), 
    setting: require('../assets/icons/setting.png'),
    Icon_feather_user : require('../assets/icons/Icon_feather_user.png'), 
    Icon_awesome_building : require('../assets/icons/Icon_awesome_building.png'), 
    up: require('../components/Collapsing/images/Arrowhead-01-128.png'),
    down: require('../components/Collapsing/images/Arrowhead-Down-01-128.png') 
};
module.exports = images;
